### ISSUE TITLE
[FEATURE] Virtual Sensor: Solar Energy

### ISSUE THREAD

**Issue by fwittenfeld** [LarsK1/hass_solvis_control#3]
Wie [**hier diskutiert**](https://community.smarthome-for-dummies.de/viewtopic.php?p=7796#p7796) ist es möglich, die über Solarthermie geerntete Energie aus der Vorlauf-/Rücklauftemperatur und dem Solardurchfluss zu errechnen.

Ich mache das derzeit so
```
sensor:     
  - platform: template
    sensors:
      solar_heat_power: 
        friendly_name: Solar Power
        #Spezifische Wärmekapazität 4,187 J/(g*K), https://www.mikrocontroller.net/topic/209838
        #1000g/liter, 3600 s/h -> 4.19*1000/3600 = 1.163
        value_template: "{{( (states('sensor.s5_solar_vl_sek') | float - states('sensor.s6_solar_rl_sek') | float) * states('sensor.solar_durchfluss') | float) * (1.16305555556) | round(2)}}"
        unit_of_measurement: W
``` 

Anders als bei dir & in der Solvis-Doku habe ich dabei die Einheit des SolarDurchfluss (33040) mit  ltr/h festgelegt.
Die an der Heizung & in HA angezeigten Werte für Durchfluss und Energie stimmen dann zumindest bei mir überein.
Wäre cool, wenn mal jemand checken könnte, ob das nur bei meiner Anlage so ist. ;-)
