### ISSUE TITLE
[Feature] Graphical presentation fo values

### ISSUE THREAD

**Issue by LarsK1** [LarsK1/hass_solvis_control#48]
How about a Solvis-Dashboard?
![2024-10-20 112325 Solvis Integration](https://github.com/user-attachments/assets/006c2e26-4db6-4b07-8502-b664be604e1e)

_Originally posted by @MAPSOFT2 in https://github.com/LarsK1/hass_solvis_control/issues/46#issuecomment-2424758500_

**Comment by timmost** [comment]
Reminds me on the online generator of Solvis. there are a ton of different configurations possible already with Solvis components.    see here... [https://www.solvis.de/online-generator/](url)

**Comment by y17dt** [comment]
I would love to have something like this. 
Maybe with toggles for Warmwater temp integrated?

**Comment by MAPSOFT2** [comment]
Another idea would be to take screenshots of 
[https://solvisportal.de/devices/system-schema](https://solvisportal.de/devices/system-schema)
and add the values at certain positions.

**Comment by nevyen** [comment]
I take a look here too. 

@MAPSOFT2  Taking a Screenshot will only allows a static representation. The graphical representation of the portal has some "intelligence". For example, when adding warm water the dashed line to the top of the Max gets straight. And the line for the Heaters gets dashed. And you have different "Screens" one for each heating source, and then warm water and maybe another one for Solar panels if installed. 

Taking a look to the portal with a developer console shows, that the graphic is represented as an <path> element. So coping all path elements do an empty html Canva will give the Graphic without any values. 

But I didn't get those Canva integrated into HA. 
And then I did run out of time to get further on this problem. 

Maybe it's possible to render some Canva into HA. 

Another Idea was to work with the remote control of the SC3. But this isn't a simple html page. And I run into the same time problem. 

I would like to have this feature too But this could be a little complicated.

**Comment by LarsK1** [comment]
This is now being actively worked on and a first release migth soon be available under: 
https://github.com/LarsK1/hass_solvis_frontend

Any feedback or help is highly appreciated

**Comment by jove01** [comment]
Meine Lösung:

<img width="550" height="402" alt="Image" src="https://github.com/user-attachments/assets/a2bfef0d-0b14-4a0b-8872-487917289e38" />

```
`    cards:
      - type: picture-elements 
        image: /local/ha_picture/solvis_hell.png
        elements:
          - type: state-badge
            entity: sensor.warmepumpe_daily_energy
            Title: Tgl. Verbrauch
            style:
              top: 10%
              left: 8%
          - type: state-label
            entity: sensor.solvis_warmepumpe_aussentemperatur_s10
            style:
              top: 10%
              left: 55%
          - type: state-label
            entity: sensor.solvis_warmepumpe_warmwassertemperatur_s2
            style:
              top: 31%
              left: 75%
          - type: state-label
            entity: sensor.solvis_warmepumpe_hkr1_vorlauftemperatur_s12
            style:
              top: 50%
              left: 75%
          - type: state-label
            entity: sensor.solvis_warmepumpe_hkr2_vorlauftemperatur_s13
            style:
              top: 68%
              left: 75%
          - type: state-label
            entity: sensor.solvis_warmepumpe_warmwasserpuffer_temperatur_s1
            prefix: "S1: "
            style:
              top: 36%
              left: 32%
          - type: state-label
            entity: sensor.solvis_warmepumpe_heizungspuffer_oben_temperatur_s4
            prefix: "S4: "
            style:
              top: 47%
              left: 32%
          - type: state-label
            entity: sensor.solvis_warmepumpe_heizungspuffer_unten_temperatur_s9
            prefix: "S9: "
            style:
              top: 62%
              left: 32%
          - type: state-label
            entity: sensor.solvis_warmepumpe_speicherreferenztemperatur_s3
            prefix: "S3: "
            style:
              top: 79%
              left: 32%
          - type: state-label
            entity: sensor.solvis_warmepumpe_kaltwassertemperatur_s15
            prefix: "Kaltw. S15: "
            style:
              top: 88%
              left: 48%
          - type: state-label
            entity: input_select.solvis_sg_ready
            prefix: "SG: "
            style:
              top: 94%
              left: 15%`
```
